HangmanWordList = ["MEME",
                   "MEMES",
                   "DAT BOI",
                   "SANIC",
                   "WEEGEE",
                   "I WONDER WHATS FOR DINNER",
                   "YTP",
                   "CRINGE",
                   "FIDGET SPINNER",
                   "DEAD MEME",
                   "MLG",
                   "AH YES THE FLOOR HERE IS MADE OF FLOOR",
                   "GET REAL",
                   "NYAN CAT",
                   "WE ARE NUMBER ONE",
                   "STEAMED HAMS",
                   "DEEZ NUTZ",
                   "GOTTEM GGS",
                   "WE LIVE IN A SOCIETY",
                   "YOUR MOM GAY",
                   "BRUH MOMENT",
                   "MEGALOVANIA",
                   "PEPE HANDS",
                   "WHY ARE WE STILL HERE"
                   "LIGMA BALLS"
                   ]